"""
The sequence of triangle numbers is generated by adding the natural numbers. So the 
7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. 

The first ten terms would be:
        1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
Let us list the factors of the first seven triangle numbers:
            1: 1
            3: 1, 3
            6: 1, 2, 3, 6
            10: 1, 2, 5, 10
            15: 1, 3, 5, 15
            21: 1, 3, 7, 21
            28: 1, 2, 4, 7, 14, 28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""

import math

# Method 1

divisors = []
i = 1
number = 0

while True:
    number += i
    sqrt_of_number = int(math.sqrt(number))

    for divisor in range(1, sqrt_of_number + 1):
        if (number % divisor == 0):
            divisors.append(divisor)

            if (divisor != number//divisor):
                divisors.append(number//divisor)
    
    number_of_divisors = len(divisors)

    if (number_of_divisors > 500):
        print(number)
        break
    else:
        divisors.clear()

    i += 1


# Method 2

i = 1
number = 0

while True:
    number += i
    number_of_divisors = 0
    sqrt_of_number = int(math.sqrt(number))

    for divisor in range(1, sqrt_of_number + 1):
        if (number % divisor == 0):
            number_of_divisors += 1

            if (divisor != number//divisor):
                number_of_divisors += 1

    if (number_of_divisors > 500):
        print(number)
        break

    i += 1
